title = "Notre-Dame de Paris"
baseURL = "https://gitreceiver.github.io/"
languageCode = "zh_CN"
theme = ["ananke"]
resourceDir = "./resources"

DefaultContentLanguage = "zh_CN"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh_CN]
    title = "申非"
    weight = 1
    languageName = 'English'
    contentDir = "content/zh"
  [languages.en]
    title = "Shenfei"
    weight = 2
    languageName = '中文'
    contentDir = "content/en"

  
[languages.zh_CN.params]
  read_more_copy = "更多"

[languages.en.params]
  read_more_copy = "Read More"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  commentoEnable = true
  show_reading_time = true


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/BruceHaww"


[services.disqus]
  shortname = 'Shenfei'
